import { Employee } from "@/types/types";

export const mockEmployees: Employee[] = [
  {
    id: 1,
    name: "Johnathan 'Jon' Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    status: true,
  },
  {
    id: 2,
    name: "Jane Anne Smith",
    email: "jane.smith@example.com",
    phone: "098-765-4321",
    status: true,
  },
  {
    id: 3,
    name: "Robert 'Bob' Johnson Jr.",
    email: "bob.johnson@example.com",
    phone: "555-123-4567",
    status: false,
  },
  {
    id: 4,
    name: "Alice Faye Williams",
    email: "alice.williams@example.com",
    phone: "555-987-6543",
    status: true,
  },
  {
    id: 5,
    name: "Charles 'Charlie' Brown",
    email: "charlie.brown@example.com",
    phone: "555-246-8135",
    status: true,
  },
];

export const getInitials = (name: string): string => {
  if (!name) return "";
  const parts = name.split(" ");
  if (parts.length === 1) return parts[0][0]?.toUpperCase() || "";
  return (parts[0][0] + (parts[parts.length - 1][0] || "")).toUpperCase();
};

import { ItemUsageRecord } from "@/types/types";

export const mockItemUsage: ItemUsageRecord[] = [
  {
    id: 1,
    employeeId: 1,
    employeeName: "John Doe",
    date: "2025-03-15",
    items: [
      { name: "Laptop", quantity: 1 },
      { name: "Mouse", quantity: 1 },
    ],
  },
  {
    id: 2,
    employeeId: 2,
    employeeName: "Jane Smith",
    date: "2025-03-16",
    items: [
      { name: "Notebook", quantity: 2 },
      { name: "Pen", quantity: 5 },
    ],
  },
  {
    id: 3,
    employeeId: 4,
    employeeName: "Alice Williams",
    date: "2025-03-18",
    items: [
      { name: "Monitor", quantity: 1 },
      { name: "Keyboard", quantity: 1 },
    ],
  },
];

import { EmployeeSelectItem } from "@/types/types";

export const mockEmployeesForItemForm: EmployeeSelectItem[] = [
  { id: 1, name: "John Doe" },
  { id: 2, name: "Jane Smith" },
  { id: 3, name: "Bob Johnson" },
  { id: 4, name: "Alice Williams" },
  { id: 5, name: "Charlie Brown" },
];

import { MonthlyAttendance, AttendanceEmployeeInfo } from "@/types/types";

export const mockEmployeesForAttendance: AttendanceEmployeeInfo[] = [
  { id: 1, name: "Johnathan 'Jon' Doe" },
  { id: 2, name: "Jane Anne Smith" },
  { id: 3, name: "Robert 'Bob' Johnson Jr." },
  { id: 4, name: "Alice Faye Williams" },
  { id: 5, name: "Charles 'Charlie' Brown" },
];

export const mockMonthlyAttendanceData: Record<string, MonthlyAttendance> = {
  "2025-03": {
    1: {
      1: true,
      2: true,
      3: false,
      4: true,
      5: true,
      6: false,
      7: false,
      8: true,
      9: true,
      10: true,
      11: true,
      12: true,
      13: false,
      14: false,
      15: true,
      16: true,
      17: true,
      18: false,
      19: true,
      20: true,
      21: false,
      22: false,
      23: true,
      24: true,
      25: true,
      26: false,
      27: true,
      28: true,
      29: false,
      30: false,
      31: true,
    },
    2: {
      1: true,
      2: true,
      3: true,
      4: true,
      5: true,
      6: false,
      7: false,
      8: true,
      9: true,
      10: true,
      11: false,
      12: true,
      13: false,
      14: false,
      15: true,
      16: true,
      17: true,
      18: true,
      19: true,
      20: true,
      21: false,
      22: false,
      23: true,
      24: true,
      25: false,
      26: true,
      27: true,
      28: true,
      29: false,
      30: false,
      31: true,
    },
    3: {
      1: false,
      2: true,
      3: true,
      4: false,
      5: true,
      6: false,
      7: false,
      8: false,
      9: true,
      10: true,
      11: true,
      12: true,
      13: false,
      14: false,
      15: true,
      16: true,
      17: false,
      18: true,
      19: true,
      20: false,
      21: false,
      22: false,
      23: true,
      24: true,
      25: true,
      26: true,
      27: true,
      28: true,
      29: false,
      30: false,
      31: false,
    },
    4: {
      1: true,
      2: true,
      3: true,
      4: true,
      5: true,
      6: false,
      7: false,
      8: true,
      9: true,
      10: true,
      11: true,
      12: true,
      13: false,
      14: false,
      15: true,
      16: true,
      17: true,
      18: true,
      19: true,
      20: true,
      21: false,
      22: false,
      23: true,
      24: true,
      25: true,
      26: true,
      27: true,
      28: true,
      29: false,
      30: false,
      31: true,
    },
    5: {
      1: true,
      2: false,
      3: true,
      4: true,
      5: false,
      6: false,
      7: false,
      8: true,
      9: false,
      10: true,
      11: true,
      12: true,
      13: false,
      14: false,
      15: true,
      16: true,
      17: true,
      18: true,
      19: false,
      20: true,
      21: false,
      22: false,
      23: true,
      24: true,
      25: true,
      26: true,
      27: false,
      28: true,
      29: false,
      30: false,
      31: true,
    },
  },
  "2025-02": {},
};
